# Generated by Django 5.1 on 2024-08-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdgblog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link To Read Blog Post.', max_length=255),
        ),
    ]
